export {default as Navbar} from './navbar.jsx';
export {default as Button} from './button.jsx';
export {default as ImageSlider} from './carousel.jsx';
export {default as Header} from './header.jsx';
export {default as Products} from './products.jsx';
export {default as Carousel} from './carousel.jsx'
export {default as Delivery} from './delivery.jsx';
export {default as Goverment} from './goverment.jsx'
export {default as Testimonals} from './testimonals.jsx';
export {default as About} from './about.jsx';
export {default as Footer} from './footer.jsx'